#!/bin/bash
#SBATCH -J ADVTest
#SBATCH -o ADVTest.o%j
#SBATCH -n 1
#SBATCH -t 01:00:00
#SBATCH -p development
#SBATCH --mail-user=mlovelace713@gmail.com
#SBATCH --mail-type=begin
#SBATCH --mail-type=end

ibrun $HOME/git/Protein_Analyzer/Loop.sh
