#!/bin/bash
#SBATCH -J ADVTest
#SBATCH -o ADVTest.o%j
#SBATCH -n 1
#SBATCH -p development
#SBATCH --mail-user=mlovelace713@gmail.com
#SBATCH --mail-type=begin
#SBATCH --mail-type=end

FILES=/$HOME/ADVFiles
for l in $FILES
do
  ibrun ./autodock_vina_1_1_2_linux_x86/bin/vina --receptor protein.pdbqt --    
  ligand $l --center_x 11 --center_y 90.5 --center_z 57.5 --size_x 22 --
  size_y 24 --size_z 28
done
